DECLARE messaging STRING;
DECLARE platform STRING;
DECLARE reliability STRING;
DECLARE crmification STRING;
DECLARE enterprise STRING;
DECLARE other STRING;

SET messaging = r'\b(chatbot|social|messaging)\b';
SET platform = r'\b(integration|apps|third-party|third party|3rd party|extensibility|objects|system|systems)\b';
SET reliability = r'\b(outage|reliability|stability|uptime|downtime|security|breach)\b';
SET crmification = r'\b(sfa|sales automation)\b';
SET enterprise = r'\b(architecture|scalability|itsm|itil|sandbox|ola|sla)\b';
SET other = r'\b(social listening|social media management|social media monitor)\b';

WITH initial_flags AS
(
    SELECT
        id,
        account_health_risk_type__c,
        description_of_risk__c,
        x2014_renewal_status_notes__c,
        churn_reason__c,
        competitive_notes__c,

        -- Autogenerated columns for category messaging
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), messaging) AS ahrt_contains_messaging,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), messaging),
                ', '
            ),
            ''
        ) AS ahrt_messaging_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), messaging) AS dor_contains_messaging,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), messaging),
                ', '
            ),
            ''
        ) AS dor_messaging_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), messaging) AS rsn_contains_messaging,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), messaging),
                ', '
            ),
            ''
        ) AS rsn_messaging_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), messaging) AS cr_contains_messaging,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), messaging),
                ', '
            ),
            ''
        ) AS cr_messaging_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), messaging) AS cn_contains_messaging,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), messaging),
                ', '
            ),
            ''
        ) AS cn_messaging_matches,


        -- Autogenerated columns for category platform
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), platform) AS ahrt_contains_platform,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), platform),
                ', '
            ),
            ''
        ) AS ahrt_platform_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), platform) AS dor_contains_platform,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), platform),
                ', '
            ),
            ''
        ) AS dor_platform_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), platform) AS rsn_contains_platform,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), platform),
                ', '
            ),
            ''
        ) AS rsn_platform_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), platform) AS cr_contains_platform,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), platform),
                ', '
            ),
            ''
        ) AS cr_platform_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), platform) AS cn_contains_platform,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), platform),
                ', '
            ),
            ''
        ) AS cn_platform_matches,


        -- Autogenerated columns for category reliability
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), reliability) AS ahrt_contains_reliability,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), reliability),
                ', '
            ),
            ''
        ) AS ahrt_reliability_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), reliability) AS dor_contains_reliability,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), reliability),
                ', '
            ),
            ''
        ) AS dor_reliability_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), reliability) AS rsn_contains_reliability,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), reliability),
                ', '
            ),
            ''
        ) AS rsn_reliability_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), reliability) AS cr_contains_reliability,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), reliability),
                ', '
            ),
            ''
        ) AS cr_reliability_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), reliability) AS cn_contains_reliability,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), reliability),
                ', '
            ),
            ''
        ) AS cn_reliability_matches,


        -- Autogenerated columns for category crmification
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), crmification) AS ahrt_contains_crmification,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), crmification),
                ', '
            ),
            ''
        ) AS ahrt_crmification_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), crmification) AS dor_contains_crmification,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), crmification),
                ', '
            ),
            ''
        ) AS dor_crmification_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), crmification) AS rsn_contains_crmification,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), crmification),
                ', '
            ),
            ''
        ) AS rsn_crmification_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), crmification) AS cr_contains_crmification,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), crmification),
                ', '
            ),
            ''
        ) AS cr_crmification_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), crmification) AS cn_contains_crmification,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), crmification),
                ', '
            ),
            ''
        ) AS cn_crmification_matches,


        -- Autogenerated columns for category enterprise
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), enterprise) AS ahrt_contains_enterprise,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), enterprise),
                ', '
            ),
            ''
        ) AS ahrt_enterprise_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), enterprise) AS dor_contains_enterprise,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), enterprise),
                ', '
            ),
            ''
        ) AS dor_enterprise_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), enterprise) AS rsn_contains_enterprise,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), enterprise),
                ', '
            ),
            ''
        ) AS rsn_enterprise_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), enterprise) AS cr_contains_enterprise,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), enterprise),
                ', '
            ),
            ''
        ) AS cr_enterprise_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), enterprise) AS cn_contains_enterprise,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), enterprise),
                ', '
            ),
            ''
        ) AS cn_enterprise_matches,


        -- Autogenerated columns for category other
        REGEXP_CONTAINS(COALESCE(LOWER(account_health_risk_type__c), ''), other) AS ahrt_contains_other,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(account_health_risk_type__c), ''), other),
                ', '
            ),
            ''
        ) AS ahrt_other_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(description_of_risk__c), ''), other) AS dor_contains_other,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(description_of_risk__c), ''), other),
                ', '
            ),
            ''
        ) AS dor_other_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), other) AS rsn_contains_other,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(x2014_renewal_status_notes__c), ''), other),
                ', '
            ),
            ''
        ) AS rsn_other_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(churn_reason__c), ''), other) AS cr_contains_other,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(churn_reason__c), ''), other),
                ', '
            ),
            ''
        ) AS cr_other_matches,
        REGEXP_CONTAINS(COALESCE(LOWER(competitive_notes__c), ''), other) AS cn_contains_other,
        NULLIF(
            ARRAY_TO_STRING(
                REGEXP_EXTRACT_ALL(COALESCE(LOWER(competitive_notes__c), ''), other),
                ', '
            ),
            ''
        ) AS cn_other_matches
    FROM sfdc.account_scd2
    WHERE dw_eff_end = '9999-12-31'
),

aggregate_flags AS
(
    SELECT
        id,
        account_health_risk_type__c,
        description_of_risk__c,
        x2014_renewal_status_notes__c,
        churn_reason__c,
        competitive_notes__c,

        -- Autogenerated top-level columns for category messaging
        ahrt_contains_messaging
            OR dor_contains_messaging
            OR rsn_contains_messaging
            OR cr_contains_messaging
            OR cn_contains_messaging
                AS any_contains_messaging,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_messaging_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_messaging_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_messaging_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_messaging_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_messaging_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_messaging_matches,

        -- Autogenerated top-level columns for category platform
        ahrt_contains_platform
            OR dor_contains_platform
            OR rsn_contains_platform
            OR cr_contains_platform
            OR cn_contains_platform
                AS any_contains_platform,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_platform_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_platform_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_platform_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_platform_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_platform_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_platform_matches,

        -- Autogenerated top-level columns for category reliability
        ahrt_contains_reliability
            OR dor_contains_reliability
            OR rsn_contains_reliability
            OR cr_contains_reliability
            OR cn_contains_reliability
                AS any_contains_reliability,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_reliability_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_reliability_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_reliability_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_reliability_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_reliability_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_reliability_matches,

        -- Autogenerated top-level columns for category crmification
        ahrt_contains_crmification
            OR dor_contains_crmification
            OR rsn_contains_crmification
            OR cr_contains_crmification
            OR cn_contains_crmification
                AS any_contains_crmification,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_crmification_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_crmification_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_crmification_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_crmification_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_crmification_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_crmification_matches,

        -- Autogenerated top-level columns for category enterprise
        ahrt_contains_enterprise
            OR dor_contains_enterprise
            OR rsn_contains_enterprise
            OR cr_contains_enterprise
            OR cn_contains_enterprise
                AS any_contains_enterprise,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_enterprise_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_enterprise_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_enterprise_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_enterprise_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_enterprise_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_enterprise_matches,

        -- Autogenerated top-level columns for category other
        ahrt_contains_other
            OR dor_contains_other
            OR rsn_contains_other
            OR cr_contains_other
            OR cn_contains_other
                AS any_contains_other,
        NULLIF(
            CONCAT(
                COALESCE(
                    CONCAT('account_health_risk_type__c: [', ahrt_other_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('description_of_risk__c: [', dor_other_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('x2014_renewal_status_notes__c: [', rsn_other_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('churn_reason__c: [', cr_other_matches, ']\n'),
                    ''
                ),
                COALESCE(
                    CONCAT('competitive_notes__c: [', cn_other_matches, ']\n'),
                    ''
                )
            ),
            ''
        ) AS all_other_matches,

        -- All flag columns from previous CTE
        ahrt_contains_messaging,
        ahrt_messaging_matches,
        dor_contains_messaging,
        dor_messaging_matches,
        rsn_contains_messaging,
        rsn_messaging_matches,
        cr_contains_messaging,
        cr_messaging_matches,
        cn_contains_messaging,
        cn_messaging_matches,
        ahrt_contains_platform,
        ahrt_platform_matches,
        dor_contains_platform,
        dor_platform_matches,
        rsn_contains_platform,
        rsn_platform_matches,
        cr_contains_platform,
        cr_platform_matches,
        cn_contains_platform,
        cn_platform_matches,
        ahrt_contains_reliability,
        ahrt_reliability_matches,
        dor_contains_reliability,
        dor_reliability_matches,
        rsn_contains_reliability,
        rsn_reliability_matches,
        cr_contains_reliability,
        cr_reliability_matches,
        cn_contains_reliability,
        cn_reliability_matches,
        ahrt_contains_crmification,
        ahrt_crmification_matches,
        dor_contains_crmification,
        dor_crmification_matches,
        rsn_contains_crmification,
        rsn_crmification_matches,
        cr_contains_crmification,
        cr_crmification_matches,
        cn_contains_crmification,
        cn_crmification_matches,
        ahrt_contains_enterprise,
        ahrt_enterprise_matches,
        dor_contains_enterprise,
        dor_enterprise_matches,
        rsn_contains_enterprise,
        rsn_enterprise_matches,
        cr_contains_enterprise,
        cr_enterprise_matches,
        cn_contains_enterprise,
        cn_enterprise_matches,
        ahrt_contains_other,
        ahrt_other_matches,
        dor_contains_other,
        dor_other_matches,
        rsn_contains_other,
        rsn_other_matches,
        cr_contains_other,
        cr_other_matches,
        cn_contains_other,
        cn_other_matches
    FROM initial_flags
)

SELECT * FROM aggregate_flags
WHERE
    any_contains_messaging
    OR any_contains_platform
    OR any_contains_reliability
    OR any_contains_crmification
    OR any_contains_enterprise
    OR any_contains_other